//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionKernelDSL.Framework.Language.CustomCode.CodeGeneration {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeGenerationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeGenerationResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransactionKernelDSL.Framework.Language.CustomCode.CodeGeneration.CodeGenerationR" +
                            "esource", typeof(CodeGenerationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CodeGeneratorTemplate {
            get {
                object obj = ResourceManager.GetObject("CodeGeneratorTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionConfigGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionConfigGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionContextGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionContextGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionContextUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionContextUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionEngineGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionEngineGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionEngineScriptGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionEngineScriptGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionEngineScriptGenerator_SatelliteInstances {
            get {
                object obj = ResourceManager.GetObject("TransactionEngineScriptGenerator_SatelliteInstances", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionFacadeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionFacadeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionFacadeScriptGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionFacadeScriptGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionFacadeScriptGenerator_SatelliteInstances {
            get {
                object obj = ResourceManager.GetObject("TransactionFacadeScriptGenerator_SatelliteInstances", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionFacadeUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionFacadeUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionHandlerForwardingUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionHandlerForwardingUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionHandlerGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionHandlerGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionHandlerListeningUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionHandlerListeningUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionHandlerMaintenanceUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionHandlerMaintenanceUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionHandlerOutputWebServiceUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionHandlerOutputWebServiceUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionHandlerSQLDataSourceScriptGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionHandlerSQLDataSourceScriptGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionHandlerSQLDataSourceUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionHandlerSQLDataSourceUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionInputEngineInputUnitTestGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionInputEngineInputUnitTestGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionInputEngineOutputUnitTestGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionInputEngineOutputUnitTestGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionInputEngineUnitTestGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionInputEngineUnitTestGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionInputEngineUnitTestUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionInputEngineUnitTestUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionInputEngineUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionInputEngineUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionOutputEngineUserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionOutputEngineUserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionOutputWebServiceScriptGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionOutputWebServiceScriptGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionOutputWebServiceScriptGenerator_SatelliteInstances {
            get {
                object obj = ResourceManager.GetObject("TransactionOutputWebServiceScriptGenerator_SatelliteInstances", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParser_InputUnitTest_UserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParser_InputUnitTest_UserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParser_UnitTestGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParser_UnitTestGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParser_UserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParser_UserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParserField_UserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParserField_UserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParserFieldGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParserFieldGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParserGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParserGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParserStream_UserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParserStream_UserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParserStreamGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParserStreamGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParserStructure_UserCustomizedCodeGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParserStructure_UserCustomizedCodeGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TransactionPropietaryParserStructureGenerator {
            get {
                object obj = ResourceManager.GetObject("TransactionPropietaryParserStructureGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
