//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionKernelDSL.Framework.Language
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "TrnxDsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"TramsactionKernelDSL.Framework.Language";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"HZ - UNLP";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID TrnxDslDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(TrnxDslCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID TrnxDslExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(TrnxDslCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewTrnxDslExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(TrnxDslCommandSetId), 0x0001);
	
		// Package identifier
		public const string TrnxDslPackageId = "5baeeeac-b2c5-4218-965b-88e4d10181bb";
		
		// Editor factory identifier
		public const string TrnxDslEditorFactoryId = "6d402703-5918-4a5a-be3f-79d73d44ab6e";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string TrnxDslModelExplorerToolWindowId = "16ee8c34-b894-4709-a0d1-ff0b5bfaa14d";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace TransactionKernelDSL.Framework.Language
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string TrnxDslCommandSetId = "98333834-4f38-4aaa-99cd-d351c46386da";
	}
}