//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace TransactionKernelDSL.Framework.Language
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class TrnxDslExplorer : TrnxDslExplorerBase
	{
		/// <summary>
		/// Constructs a new TrnxDslExplorer.
		/// </summary>
		public TrnxDslExplorer(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}
	
	/// <summary>
	/// Control hosted in the TrnxDslExplorerToolWindow.
	/// </summary>
	internal abstract class TrnxDslExplorerBase : DslShell::ModelExplorerTreeContainer
	{
		/// <summary>
		/// Constructs a new TrnxDslExplorerBase.
		/// </summary>
		protected TrnxDslExplorerBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
			
			
			// Adds custom tree node settings...
			global::System.Resources.ResourceManager resourceManager = global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel.SingletonResourceManager;
			
			this.AddExplorerNodeCustomSetting(global::TransactionKernelDSL.Framework.Language.InputTransactionEngine.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InputTransactionEngineExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OutputTransactionEngineExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::TransactionKernelDSL.Framework.Language.OutputTransactionWebService.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OutputTransactionWebServiceExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::TransactionKernelDSL.Framework.Language.TransactionHandler.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionHandlerExplorerImage")), 
							false); 
			
			// Add a call back to provide ModelElementTreeNode TreeNode name in the Model Explorer
			this.GetModelElementDisplayNameEventHandler = new DslShell.GetModelElementDisplayNameEventHandler(GetModelElementDisplayName);
		}
	
	
	
		/// <summary>
		/// Create IElementVisitor
		/// </summary>
		/// <returns>IElementVisitor</returns>
		protected override DslModeling::IElementVisitor CreateElementVisitor()
		{
			return new DslShell::ExplorerElementVisitor(this);
		}
	
		/// <summary>
		/// Specifies the context menu that should be shown for the model explorer.
		///</summary>
		protected override global::System.ComponentModel.Design.CommandID ContextMenuCommandId
		{
			get
			{
				return Constants.TrnxDslExplorerMenu;
			}
		}
		
		/// <summary>
		/// Returns the root elements domain class Id. The is the very top level tree node in the TreeView
		///</summary>
		protected override global::System.Guid RootElementDomainClassId
		{
			get { return global::TransactionKernelDSL.Framework.Language.TransactionModel.DomainClassId; }
		}
		
		/// <summary>
		/// Returns the root elements to be displayed in the explorer.
		///</summary>
		protected override global::System.Collections.IList FindRootElements(DslModeling::Store store)
		{
			return store.ElementDirectory.FindElements( this.RootElementDomainClassId);
		}
			
		/// <summary>
		/// Method to supply the name for ModelElementTreeNode object in the TreeView.
		/// </summary>
		/// <param name="modelElement">Element to be displayed in the tree node</param>
		/// <returns>Name shown in the Model Explorer</returns>
		private string GetModelElementDisplayName(DslModeling::ModelElement modelElement)
		{
			string treeNodeDisplayName = null;
			DslModeling::DomainDataDirectory directory = modelElement.Store.DomainDataDirectory;
			DslModeling::DomainPropertyInfo domainPropertyInfo = null;
			DslModeling::ModelElement redirectedElement = null;
			
			switch ( modelElement.GetDomainClass().Id.ToString( "D", System.Globalization.CultureInfo.InvariantCulture) )
			{
				case "2d46088e-0b4e-43d2-8cac-17dfdd93f58b":	// InputTransactionEngine.DomainClassId
				{
					domainPropertyInfo = directory.FindDomainProperty( global::TransactionKernelDSL.Framework.Language.TransactionEngine.NameDomainPropertyId);
					redirectedElement = modelElement;
				}			
				break;
				
				case "a7a60d2a-fabc-4674-915e-4b5973256959":	// OutputTransactionEngine.DomainClassId
				{
					domainPropertyInfo = directory.FindDomainProperty( global::TransactionKernelDSL.Framework.Language.TransactionEngine.NameDomainPropertyId);
					redirectedElement = modelElement;
				}			
				break;
				
				case "407dac2b-f175-4575-a1c3-641bdec4cf8b":	// OutputTransactionWebService.DomainClassId
				{
					domainPropertyInfo = directory.FindDomainProperty( global::TransactionKernelDSL.Framework.Language.TransactionWebService.NameDomainPropertyId);
					redirectedElement = modelElement;
				}			
				break;
				
				case "1cdb00e4-ec80-43a4-8912-07403efeeaf5":	// TransactionHandler.DomainClassId
				{
					domainPropertyInfo = directory.FindDomainProperty( global::TransactionKernelDSL.Framework.Language.TransactionHandler.NameDomainPropertyId);
					redirectedElement = modelElement;
				}			
				break;
				
		
			}
			
			if (domainPropertyInfo != null && redirectedElement != null)
			{
				// Get the name based on the designated domian property
				treeNodeDisplayName = domainPropertyInfo.GetValue(redirectedElement) as string;
			}
			else
			{
				// The passed in modelElement does not have a DomainPath specified. Try access the default name from the element.
				DslModeling::DomainClassInfo.TryGetName(modelElement, out treeNodeDisplayName);
			}
			return treeNodeDisplayName;
		}
	}
}
	


