//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace TransactionKernelDSL.Framework.Language
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\11.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(TrnxDslExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(TrnxDslExplorerToolWindow), Constants.TrnxDslEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@Transaction Model ElementsToolboxTab;TransactionKernelDSL.Framework.Language.Dsl.dll", "TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab",
					"@OutputWebServiceLinkToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.OutputWebServiceLinkToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OutputWebServiceLinkTool", 
					"@OutputWebServiceLinkToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab",
					"@OutputWebServiceToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.OutputWebServiceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OutputWebServiceTool", 
					"@OutputWebServiceToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab",
					"@TimeTriggerToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TimeTriggerToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TimeTriggerTool", 
					"@TimeTriggerToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab",
					"@TimeTriggerLinkToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TimeTriggerLinkToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TimeTriggerLinkTool", 
					"@TimeTriggerLinkToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxGroup("@EnginesToolboxTab;TransactionKernelDSL.Framework.Language.Dsl.dll", "TransactionKernelDSL.Framework.Language.EnginesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.EnginesToolboxTab",
					"@InputTransactionEngineToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.InputTransactionEngineToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InputTransactionEngineTool", 
					"@InputTransactionEngineToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.EnginesToolboxTab",
					"@InputLinkToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.InputLinkToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InputLinkTool", 
					"@InputLinkToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.EnginesToolboxTab",
					"@OutputTransactionEngineToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.OutputTransactionEngineToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OutputTransactionEngineTool", 
					"@OutputTransactionEngineToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.EnginesToolboxTab",
					"@OutputLinkToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.OutputLinkToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OutputLinkTool", 
					"@OutputLinkToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.EnginesToolboxTab",
					"@TransactionDataSourceSupportForOutputEngineLinkToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportForOutputEngineLinkToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionDataSourceSupportForOutputEngineLinkTool", 
					"@TransactionDataSourceSupportForOutputEngineLinkToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxGroup("@HandlersToolboxTab;TransactionKernelDSL.Framework.Language.Dsl.dll", "TransactionKernelDSL.Framework.Language.HandlersToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.HandlersToolboxTab",
					"@TransactionHandlerToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionHandlerToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateExampleClassF1Keyword", 
					"@TransactionHandlerToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.HandlersToolboxTab",
					"@TransactionHandlerForwardingLinkToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionHandlerForwardingLinkToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectExampleRelationF1Keyword", 
					"@TransactionHandlerForwardingLinkToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.HandlersToolboxTab",
					"@TransactionHandlerMaintenanceLinkToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionHandlerMaintenanceLinkToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionHandlerMaintenanceLinkTool", 
					"@TransactionHandlerMaintenanceLinkToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.HandlersToolboxTab",
					"@TransactionSQLServerDataSourceLinkConnectionToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceLinkConnectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionSQLServerDataSourceLinkConnectionTool", 
					"@TransactionSQLServerDataSourceLinkConnectionToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxGroup("@LayersToolboxTab;TransactionKernelDSL.Framework.Language.Dsl.dll", "TransactionKernelDSL.Framework.Language.LayersToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.LayersToolboxTab",
					"@TransactionLayerToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionLayerToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionLayerTool", 
					"@TransactionLayerToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.LayersToolboxTab",
					"@TransactionEnvironmentLayerToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayerToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionEnvironmentLayerTool", 
					"@TransactionEnvironmentLayerToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxGroup("@Data SourcesToolboxTab;TransactionKernelDSL.Framework.Language.Dsl.dll", "TransactionKernelDSL.Framework.Language.Data SourcesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.Data SourcesToolboxTab",
					"@TransactionSQLServerDataSourceToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionSQLServerDataSourceTool", 
					"@TransactionSQLServerDataSourceToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.Data SourcesToolboxTab",
					"@TransactionDataSourceSupportToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionDataSourceSupportTool", 
					"@TransactionDataSourceSupportToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxGroup("@EnvironmentToolboxTab;TransactionKernelDSL.Framework.Language.Dsl.dll", "TransactionKernelDSL.Framework.Language.EnvironmentToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("TransactionKernelDSL.Framework.Language.EnvironmentToolboxTab",
					"@TransactionEnvironmentSQLServerVariableToolToolboxItem;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					"TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariableToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionEnvironmentSQLServerVariableTool", 
					"@TransactionEnvironmentSQLServerVariableToolToolboxBitmap;TransactionKernelDSL.Framework.Language.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideEditorFactory(typeof(TrnxDslEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(TrnxDslEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(TrnxDslEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"TrnxDsl", typeof(TrnxDslEditorFactory))]

	internal abstract partial class TrnxDslPackageBase : DslShell::ModelingPackage
	{
		protected global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new TrnxDslEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			TrnxDslCommandSet commandSet = new TrnxDslCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			TrnxDslClipboardCommandSet clipboardCommandSet = new TrnxDslClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(TrnxDslExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace TransactionKernelDSL.Framework.Language
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::TransactionKernelDSL.Framework.Language.TrnxDslDirectiveProcessor), global::TransactionKernelDSL.Framework.Language.TrnxDslDirectiveProcessor.TrnxDslDirectiveProcessorName, "A directive processor that provides access to TrnxDsl files")]
	[global::System.Runtime.InteropServices.Guid(Constants.TrnxDslPackageId)]
	internal sealed partial class TrnxDslPackage : TrnxDslPackageBase
	{
	}
}