//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionKernelDSL.Framework.Parser.Iso8583_1993.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransactionKernelDSL.Framework.Parser.Iso8583_1993.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKN04 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKN04 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKN04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKNC0 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNC0 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNC0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKNC4 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNC4 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token header formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNHeader {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKNQ1 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNQ1 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKNQ2 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNQ2 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKNQ6 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNQ6 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKNU1 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNU1 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY_EXT not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_CITY_EXT {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_CITY_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE_TRACK2_DATA not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_COMPLETE_TRACK2_DATA {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_COMPLETE_TRACK2_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRD_VRFY_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_CRD_VRFY_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_CRD_VRFY_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERR_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_ERR_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_ERR_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTE_GRP not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_RTE_GRP {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_RTE_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAF_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_UAF_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_UAF_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADNL_DATA_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_ADNL_DATA_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_ADNL_DATA_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHN_COLL_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_AUTHN_COLL_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_AUTHN_COLL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAVV_AAV_RSLT_CDE not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CAVV_AAV_RSLT_CDE {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CAVV_AAV_RSLT_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRCL_CRD_TYP not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CMRCL_CRD_TYP {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CMRCL_CRD_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVD_FLD not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CVD_FLD {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CVD_FLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVD_FLD_PRESENT not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CVD_FLD_PRESENT {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CVD_FLD_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_COM_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_E_COM_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_E_COM_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRD_PRN_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_FRD_PRN_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_FRD_PRN_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTO_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_MOTO_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_MOTO_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESUB_CNTR not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_RESUB_CNTR {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_RESUB_CNTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESUB_STAT not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_RESUB_STAT {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_RESUB_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAF_OR_FORCE_POST not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_SAF_OR_FORCE_POST {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_SAF_OR_FORCE_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_POSTAL_CDE not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_TERM_POSTAL_CDE {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_TERM_POSTAL_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRD_CAPTR_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRD_CAPTR_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRD_CAPTR_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRD_PRESENT_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRD_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRD_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRDHLDR_ACTVT_TERM_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRDHLDR_ACTVT_TERM_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRDHLDR_ACTVT_TERM_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRDHLDR_ID not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRDHLDR_ID_METHOD {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRDHLDR_ID_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRDHLDR_PRESENT_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRDHLDR_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRDHLDR_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_ATTEND_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TERM_ATTEND_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TERM_ATTEND_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_INPUT_CAP_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TERM_INPUT_CAP_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TERM_INPUT_CAP_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_LOC_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TERM_LOC_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TERM_LOC_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXN_STAT_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TXN_STAT_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TXN_STAT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLY not initialized.
        /// </summary>
        internal static string ErrorGet_TKNQ6_DLY {
            get {
                return ResourceManager.GetString("ErrorGet_TKNQ6_DLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INST not initialized.
        /// </summary>
        internal static string ErrorGet_TKNQ6_INST {
            get {
                return ResourceManager.GetString("ErrorGet_TKNQ6_INST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORR_PAN length must be 16.
        /// </summary>
        internal static string ErrorGet_TKNR1_CORR_PAN {
            get {
                return ResourceManager.GetString("ErrorGet_TKNR1_CORR_PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH_ACCT_BAL not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_CASH_ACCT_BAL {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_CASH_ACCT_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH_ACCT_BAL_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_CASH_ACCT_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_CASH_ACCT_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD_STMP_BAL not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_FOOD_STMP_BAL {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_FOOD_STMP_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD_STMP_BAL_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_FOOD_STMP_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_FOOD_STMP_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY_EXT length not within 5 chars.
        /// </summary>
        internal static string ErrorSet_TKN04_CITY_EXT {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_CITY_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE_TRACK2_DATA length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_COMPLETE_TRACK2_DATA {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_COMPLETE_TRACK2_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRD_VRFY_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_CRD_VRFY_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_CRD_VRFY_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERR_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_ERR_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_ERR_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTE_GRP length not within 11 chars.
        /// </summary>
        internal static string ErrorSet_TKN04_RTE_GRP {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_RTE_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAF_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_UAF_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_UAF_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADNL_DATA_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_ADNL_DATA_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_ADNL_DATA_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHN_COLL_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_AUTHN_COLL_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_AUTHN_COLL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAVV_AAV_RSLT_CDE length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_CAVV_AAV_RSLT_CDE {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CAVV_AAV_RSLT_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRCL_CRD_TYP length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_CMRCL_CRD_TYP {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CMRCL_CRD_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVD_FLD length not within 4chars.
        /// </summary>
        internal static string ErrorSet_TKNC0_CVD_FLD {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CVD_FLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVD_FLD_PRESENT length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_CVD_FLD_PRESENT {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CVD_FLD_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_COM_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_E_COM_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_E_COM_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRD_PRN_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_FRD_PRN_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_FRD_PRN_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTO_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_MOTO_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_MOTO_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESUB_CNTR length not within 3 chars.
        /// </summary>
        internal static string ErrorSet_TKNC0_RESUB_CNTR {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_RESUB_CNTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESUB_STAT length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_RESUB_STAT {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_RESUB_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAF_OR_FORCE_POST length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_SAF_OR_FORCE_POST {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_SAF_OR_FORCE_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_POSTAL_CDE length not within 10 chars.
        /// </summary>
        internal static string ErrorSet_TKNC0_TERM_POSTAL_CDE {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_TERM_POSTAL_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRD_CAPTR_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRD_CAPTR_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRD_CAPTR_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRD_PRESENT_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRD_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRD_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRDHLDR_ACTVT_TERM_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRDHLDR_ACTVT_TERM_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRDHLDR_ACTVT_TERM_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRDHLDR_ID_METHOD length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRDHLDR_ID_METHOD {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRDHLDR_ID_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRDHLDR_PRESENT_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRDHLDR_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRDHLDR_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_ATTEND_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TERM_ATTEND_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TERM_ATTEND_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_INPUT_CAP_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TERM_INPUT_CAP_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TERM_INPUT_CAP_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM_LOC_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TERM_LOC_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TERM_LOC_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXN_STAT_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TXN_STAT_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TXN_STAT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH_MODE_ID length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNQ1_AUTH_MODE_ID {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ1_AUTH_MODE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACC_ID length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ2_ACC_ID {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ2_ACC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLY length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ6_DLY {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ6_DLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INST length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ6_INST {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ6_INST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ6_PLAN {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ6_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH_ACCT_BAL length must be within 18.
        /// </summary>
        internal static string ErrorSet_TKNU1_CASH_ACCT_BAL {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_CASH_ACCT_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH_ACCT_BAL_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNU1_CASH_ACCT_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_CASH_ACCT_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD_STMP_BAL length must be within 18.
        /// </summary>
        internal static string ErrorSet_TKNU1_FOOD_STMP_BAL {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_FOOD_STMP_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD_STMP_BAL_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNU1_FOOD_STMP_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_FOOD_STMP_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token couldn&apos;t be assembled!.
        /// </summary>
        internal static string ErrorToString_TKN {
            get {
                return ResourceManager.GetString("ErrorToString_TKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token header values not initialized!.
        /// </summary>
        internal static string ErrorToString_TKNHeader {
            get {
                return ResourceManager.GetString("ErrorToString_TKNHeader", resourceCulture);
            }
        }
    }
}
