//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionKernelDSL.Framework.Parser.Iso8583B24.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransactionKernelDSL.Framework.Parser.Iso8583B24.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TKN04 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKN04 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKN04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TKNC0 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNC0 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNC0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TKNC4 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNC4 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token header formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNHeader {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TKNQ1 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNQ1 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TKNQ2 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNQ2 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TKNQ6 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNQ6 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TKNU1 formed bad!.
        /// </summary>
        internal static string ErrorCtor_TKNU1 {
            get {
                return ResourceManager.GetString("ErrorCtor_TKNU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CITY_EXT not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_CITY_EXT {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_CITY_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPLETE_TRACK2_DATA not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_COMPLETE_TRACK2_DATA {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_COMPLETE_TRACK2_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRD_VRFY_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_CRD_VRFY_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_CRD_VRFY_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERR_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_ERR_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_ERR_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RTE_GRP not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_RTE_GRP {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_RTE_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UAF_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKN04_UAF_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKN04_UAF_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADNL_DATA_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_ADNL_DATA_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_ADNL_DATA_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTHN_COLL_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_AUTHN_COLL_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_AUTHN_COLL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAVV_AAV_RSLT_CDE not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CAVV_AAV_RSLT_CDE {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CAVV_AAV_RSLT_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CMRCL_CRD_TYP not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CMRCL_CRD_TYP {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CMRCL_CRD_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVD_FLD not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CVD_FLD {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CVD_FLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVD_FLD_PRESENT not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_CVD_FLD_PRESENT {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_CVD_FLD_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E_COM_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_E_COM_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_E_COM_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FRD_PRN_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_FRD_PRN_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_FRD_PRN_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTO_FLG not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_MOTO_FLG {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_MOTO_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESUB_CNTR not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_RESUB_CNTR {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_RESUB_CNTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESUB_STAT not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_RESUB_STAT {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_RESUB_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAF_OR_FORCE_POST not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_SAF_OR_FORCE_POST {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_SAF_OR_FORCE_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_POSTAL_CDE not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC0_TERM_POSTAL_CDE {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC0_TERM_POSTAL_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRD_CAPTR_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRD_CAPTR_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRD_CAPTR_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRD_PRESENT_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRD_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRD_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRDHLDR_ACTVT_TERM_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRDHLDR_ACTVT_TERM_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRDHLDR_ACTVT_TERM_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRDHLDR_ID not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRDHLDR_ID_METHOD {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRDHLDR_ID_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRDHLDR_PRESENT_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_CRDHLDR_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_CRDHLDR_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_ATTEND_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TERM_ATTEND_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TERM_ATTEND_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_INPUT_CAP_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TERM_INPUT_CAP_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TERM_INPUT_CAP_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_LOC_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TERM_LOC_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TERM_LOC_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TXN_STAT_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNC4_TXN_STAT_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNC4_TXN_STAT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DLY not initialized.
        /// </summary>
        internal static string ErrorGet_TKNQ6_DLY {
            get {
                return ResourceManager.GetString("ErrorGet_TKNQ6_DLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INST not initialized.
        /// </summary>
        internal static string ErrorGet_TKNQ6_INST {
            get {
                return ResourceManager.GetString("ErrorGet_TKNQ6_INST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORR_PAN length must be 16.
        /// </summary>
        internal static string ErrorGet_TKNR1_CORR_PAN {
            get {
                return ResourceManager.GetString("ErrorGet_TKNR1_CORR_PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CASH_ACCT_BAL not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_CASH_ACCT_BAL {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_CASH_ACCT_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CASH_ACCT_BAL_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_CASH_ACCT_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_CASH_ACCT_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOOD_STMP_BAL not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_FOOD_STMP_BAL {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_FOOD_STMP_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOOD_STMP_BAL_IND not initialized.
        /// </summary>
        internal static string ErrorGet_TKNU1_FOOD_STMP_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorGet_TKNU1_FOOD_STMP_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CITY_EXT length not within 5 chars.
        /// </summary>
        internal static string ErrorSet_TKN04_CITY_EXT {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_CITY_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPLETE_TRACK2_DATA length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_COMPLETE_TRACK2_DATA {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_COMPLETE_TRACK2_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRD_VRFY_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_CRD_VRFY_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_CRD_VRFY_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERR_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_ERR_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_ERR_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RTE_GRP length not within 11 chars.
        /// </summary>
        internal static string ErrorSet_TKN04_RTE_GRP {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_RTE_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UAF_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKN04_UAF_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKN04_UAF_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADNL_DATA_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_ADNL_DATA_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_ADNL_DATA_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTHN_COLL_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_AUTHN_COLL_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_AUTHN_COLL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAVV_AAV_RSLT_CDE length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_CAVV_AAV_RSLT_CDE {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CAVV_AAV_RSLT_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CMRCL_CRD_TYP length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_CMRCL_CRD_TYP {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CMRCL_CRD_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVD_FLD length not within 4chars.
        /// </summary>
        internal static string ErrorSet_TKNC0_CVD_FLD {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CVD_FLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVD_FLD_PRESENT length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_CVD_FLD_PRESENT {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_CVD_FLD_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E_COM_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_E_COM_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_E_COM_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FRD_PRN_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_FRD_PRN_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_FRD_PRN_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTO_FLG length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_MOTO_FLG {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_MOTO_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESUB_CNTR length not within 3 chars.
        /// </summary>
        internal static string ErrorSet_TKNC0_RESUB_CNTR {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_RESUB_CNTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESUB_STAT length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_RESUB_STAT {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_RESUB_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAF_OR_FORCE_POST length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC0_SAF_OR_FORCE_POST {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_SAF_OR_FORCE_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_POSTAL_CDE length not within 10 chars.
        /// </summary>
        internal static string ErrorSet_TKNC0_TERM_POSTAL_CDE {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC0_TERM_POSTAL_CDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRD_CAPTR_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRD_CAPTR_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRD_CAPTR_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRD_PRESENT_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRD_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRD_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRDHLDR_ACTVT_TERM_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRDHLDR_ACTVT_TERM_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRDHLDR_ACTVT_TERM_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRDHLDR_ID_METHOD length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRDHLDR_ID_METHOD {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRDHLDR_ID_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRDHLDR_PRESENT_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_CRDHLDR_PRESENT_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_CRDHLDR_PRESENT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_ATTEND_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TERM_ATTEND_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TERM_ATTEND_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_INPUT_CAP_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TERM_INPUT_CAP_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TERM_INPUT_CAP_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TERM_LOC_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TERM_LOC_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TERM_LOC_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TXN_STAT_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNC4_TXN_STAT_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNC4_TXN_STAT_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTH_MODE_ID length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNQ1_AUTH_MODE_ID {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ1_AUTH_MODE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACC_ID length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ2_ACC_ID {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ2_ACC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DLY length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ6_DLY {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ6_DLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INST length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ6_INST {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ6_INST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAN length must be 2.
        /// </summary>
        internal static string ErrorSet_TKNQ6_PLAN {
            get {
                return ResourceManager.GetString("ErrorSet_TKNQ6_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CASH_ACCT_BAL length must be within 18.
        /// </summary>
        internal static string ErrorSet_TKNU1_CASH_ACCT_BAL {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_CASH_ACCT_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CASH_ACCT_BAL_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNU1_CASH_ACCT_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_CASH_ACCT_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOOD_STMP_BAL length must be within 18.
        /// </summary>
        internal static string ErrorSet_TKNU1_FOOD_STMP_BAL {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_FOOD_STMP_BAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOOD_STMP_BAL_IND length must be 1.
        /// </summary>
        internal static string ErrorSet_TKNU1_FOOD_STMP_BAL_IND {
            get {
                return ResourceManager.GetString("ErrorSet_TKNU1_FOOD_STMP_BAL_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token couldn&apos;t be assembled!.
        /// </summary>
        internal static string ErrorToString_TKN {
            get {
                return ResourceManager.GetString("ErrorToString_TKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token header values not initialized!.
        /// </summary>
        internal static string ErrorToString_TKNHeader {
            get {
                return ResourceManager.GetString("ErrorToString_TKNHeader", resourceCulture);
            }
        }
    }
}
