//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "TransactionKernelDSL.Framework.Language.TrnxDslDiagram")]

namespace TransactionKernelDSL.Framework.Language
{
	/// <summary>
	/// DomainClass TrnxDslDiagram
	/// Description for TransactionKernelDSL.Framework.Language.TrnxDslDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("TransactionKernelDSL.Framework.Language.TrnxDslDiagram.DisplayName", typeof(global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel), "TransactionKernelDSL.Framework.Language.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("TransactionKernelDSL.Framework.Language.TrnxDslDiagram.Description", typeof(global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel), "TransactionKernelDSL.Framework.Language.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("77f68ba6-65e6-488c-a7bb-228f13951eb1")]
	public partial class TrnxDslDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Swimlane support
		
		/// <summary>
		/// Gets whether or not swimlanes are supported in this Diagram.
		/// </summary>
		public override bool HasSwimlanes
		{
			get { return true; }
		}
		
		/// <summary>
		/// Initializes the starting swimlanes in a new Diagram.
		/// </summary>
		/// <remarks>
		/// This method is not called during successful deserialization, only when either a blank diagram is created or diagram deserialization fails and a diagram is created to make things work.
		/// 
		/// This method does not create shapes for swimlanes with shape maps specified in the DSL definition, only those swimlanes which are not mapped.
		/// The assumption here is that if a swimlane is mapped to a domain class, then an instance of that class  will be created when the element mapped to the diagram is created,
		/// and swimlane shapes will be created as part of view fixup.
		/// </remarks>
		internal virtual void InitializeSwimlanes()
		{
		}
		
		/// <summary>
		/// Gets a collection of domain classes which are mapped to swimlane shapes.
		/// </summary>
		public override sealed global::System.Collections.Generic.IEnumerable<DslModeling::DomainClassInfo> CreatableSwimLaneSubjects
		{
			get
			{
				yield return this.Store.DomainDataDirectory.GetDomainClass(typeof(global::TransactionKernelDSL.Framework.Language.TransactionLayer));
				yield return this.Store.DomainDataDirectory.GetDomainClass(typeof(global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer));
			}
		}
		
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			// If in Undo, Redo or Rollback the compartment item rules are not run so we must refresh the compartment list at this point if required
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemAddRule.ElementAdded(e, repaintOnly);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemDeleteRule.ElementDeleted(e, repaintOnly);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemChangeRule.ElementPropertyChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			bool repaintOnly = !e.ElementLink.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			bool repaintOnly = !e.Link.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, repaintOnly);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::TransactionKernelDSL.Framework.Language.InputTransactionEngine)
			{
				global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape newShape = new global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine)
			{
				global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape newShape = new global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionDataSourceShape newShape = new global::TransactionKernelDSL.Framework.Language.TransactionDataSourceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.OutputTransactionWebService)
			{
				global::TransactionKernelDSL.Framework.Language.OutputTransactionWebServiceShape newShape = new global::TransactionKernelDSL.Framework.Language.OutputTransactionWebServiceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionLayer)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionLayerSwimLane newShape = new global::TransactionKernelDSL.Framework.Language.TransactionLayerSwimLane(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TimeTrigger)
			{
				global::TransactionKernelDSL.Framework.Language.TimeTriggerImageShape newShape = new global::TransactionKernelDSL.Framework.Language.TimeTriggerImageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportShape newShape = new global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTimeTriggers)
			{
				global::TransactionKernelDSL.Framework.Language.TimeTriggerLinkConnector newShape = new global::TransactionKernelDSL.Framework.Language.TimeTriggerLinkConnector(this.Partition);
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariable)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariableShape newShape = new global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariableShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayerSwimLane newShape = new global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayerSwimLane(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine)
			{
				global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineReferencesTransactionHandlersLinkConnector newShape = new global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineReferencesTransactionHandlersLinkConnector(this.Partition);
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesForwarderTransactionHandlers)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionHandlerForwardingLinkConnector newShape = new global::TransactionKernelDSL.Framework.Language.TransactionHandlerForwardingLinkConnector(this.Partition);
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers)
			{
				global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlersLinkConnector newShape = new global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlersLinkConnector(this.Partition);
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesTransactionSQLServerDataSources)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceLinkConnector newShape = new global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceLinkConnector(this.Partition);
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionWebService)
			{
				global::TransactionKernelDSL.Framework.Language.OutputTransactionWebServiceLinkConnector newShape = new global::TransactionKernelDSL.Framework.Language.OutputTransactionWebServiceLinkConnector(this.Partition);
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionHandler)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionHandlerShape newShape = new global::TransactionKernelDSL.Framework.Language.TransactionHandlerShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesMaintenanceTransactionHandler)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionHandlerMaintenanceLinkConnector newShape = new global::TransactionKernelDSL.Framework.Language.TransactionHandlerMaintenanceLinkConnector(this.Partition);
				return newShape;
			}
			if(element is global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineReferencesTransactionDataSourceSupport)
			{
				global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportForOutputEngineLink newShape = new global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportForOutputEngineLink(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::TransactionKernelDSL.Framework.Language.TransactionHandlerShape.DecoratorsInitialized += TransactionHandlerShapeDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.TransactionLayerSwimLane.DecoratorsInitialized += TransactionLayerSwimLaneDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape.DecoratorsInitialized += InputTransactionEngineShapeDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape.DecoratorsInitialized += OutputTransactionEngineShapeDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.TransactionDataSourceShape.DecoratorsInitialized += TransactionDataSourceShapeDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.OutputTransactionWebServiceShape.DecoratorsInitialized += OutputTransactionWebServiceShapeDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.TimeTriggerImageShape.DecoratorsInitialized += TimeTriggerImageShapeDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportShape.DecoratorsInitialized += TransactionDataSourceSupportShapeDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayerSwimLane.DecoratorsInitialized += TransactionEnvironmentLayerSwimLaneDecoratorMap.OnDecoratorsInitialized;
			global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariableShape.DecoratorsInitialized += TransactionEnvironmentSQLServerVariableShapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TransactionHandlerShape.
		/// </summary>
		internal static partial class TransactionHandlerShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TransactionHandlerShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionHandler.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionHandler.TransactionIdDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TransactionIdDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TransactionLayerSwimLane.
		/// </summary>
		internal static partial class TransactionLayerSwimLaneDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TransactionLayerSwimLane.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionLayer.LevelDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "LevelDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionLayer.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for InputTransactionEngineShape.
		/// </summary>
		internal static partial class InputTransactionEngineShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for InputTransactionEngineShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionEngine.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.InputTransactionEngine.TypeDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TypeDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for OutputTransactionEngineShape.
		/// </summary>
		internal static partial class OutputTransactionEngineShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for OutputTransactionEngineShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionEngine.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine.TypeDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TypeDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TransactionDataSourceShape.
		/// </summary>
		internal static partial class TransactionDataSourceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TransactionDataSourceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionDataSource.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionDataSource.StepOrderDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "StepOrderDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for OutputTransactionWebServiceShape.
		/// </summary>
		internal static partial class OutputTransactionWebServiceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for OutputTransactionWebServiceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionWebService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionWebService.WebServiceClassNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "WebServiceClassNameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TimeTriggerImageShape.
		/// </summary>
		internal static partial class TimeTriggerImageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TimeTriggerImageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TimeTrigger.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TransactionDataSourceSupportShape.
		/// </summary>
		internal static partial class TransactionDataSourceSupportShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TransactionDataSourceSupportShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TransactionEnvironmentLayerSwimLane.
		/// </summary>
		internal static partial class TransactionEnvironmentLayerSwimLaneDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TransactionEnvironmentLayerSwimLane.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TransactionEnvironmentSQLServerVariableShape.
		/// </summary>
		internal static partial class TransactionEnvironmentSQLServerVariableShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TransactionEnvironmentSQLServerVariableShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariable.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::TransactionKernelDSL.Framework.Language.OutputWebServiceLinkToolConnectAction outputWebServiceLinkToolConnectAction;
		private global::TransactionKernelDSL.Framework.Language.TimeTriggerLinkToolConnectAction timeTriggerLinkToolConnectAction;
		private global::TransactionKernelDSL.Framework.Language.InputLinkToolConnectAction inputLinkToolConnectAction;
		private global::TransactionKernelDSL.Framework.Language.OutputLinkToolConnectAction outputLinkToolConnectAction;
		private global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportForOutputEngineLinkToolConnectAction transactionDataSourceSupportForOutputEngineLinkToolConnectAction;
		private global::TransactionKernelDSL.Framework.Language.TransactionHandlerForwardingLinkToolConnectAction transactionHandlerForwardingLinkToolConnectAction;
		private global::TransactionKernelDSL.Framework.Language.TransactionHandlerMaintenanceLinkToolConnectAction transactionHandlerMaintenanceLinkToolConnectAction;
		private global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceLinkConnectionToolConnectAction transactionSQLServerDataSourceLinkConnectionToolConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.OutputWebServiceLinkToolFilterString))
				{
					if (this.outputWebServiceLinkToolConnectAction == null)
					{
						this.outputWebServiceLinkToolConnectAction = new global::TransactionKernelDSL.Framework.Language.OutputWebServiceLinkToolConnectAction(this);
						this.outputWebServiceLinkToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.outputWebServiceLinkToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.TimeTriggerLinkToolFilterString))
				{
					if (this.timeTriggerLinkToolConnectAction == null)
					{
						this.timeTriggerLinkToolConnectAction = new global::TransactionKernelDSL.Framework.Language.TimeTriggerLinkToolConnectAction(this);
						this.timeTriggerLinkToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.timeTriggerLinkToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.InputLinkToolFilterString))
				{
					if (this.inputLinkToolConnectAction == null)
					{
						this.inputLinkToolConnectAction = new global::TransactionKernelDSL.Framework.Language.InputLinkToolConnectAction(this);
						this.inputLinkToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.inputLinkToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.OutputLinkToolFilterString))
				{
					if (this.outputLinkToolConnectAction == null)
					{
						this.outputLinkToolConnectAction = new global::TransactionKernelDSL.Framework.Language.OutputLinkToolConnectAction(this);
						this.outputLinkToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.outputLinkToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.TransactionDataSourceSupportForOutputEngineLinkToolFilterString))
				{
					if (this.transactionDataSourceSupportForOutputEngineLinkToolConnectAction == null)
					{
						this.transactionDataSourceSupportForOutputEngineLinkToolConnectAction = new global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportForOutputEngineLinkToolConnectAction(this);
						this.transactionDataSourceSupportForOutputEngineLinkToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.transactionDataSourceSupportForOutputEngineLinkToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.TransactionHandlerForwardingLinkToolFilterString))
				{
					if (this.transactionHandlerForwardingLinkToolConnectAction == null)
					{
						this.transactionHandlerForwardingLinkToolConnectAction = new global::TransactionKernelDSL.Framework.Language.TransactionHandlerForwardingLinkToolConnectAction(this);
						this.transactionHandlerForwardingLinkToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.transactionHandlerForwardingLinkToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.TransactionHandlerMaintenanceLinkToolFilterString))
				{
					if (this.transactionHandlerMaintenanceLinkToolConnectAction == null)
					{
						this.transactionHandlerMaintenanceLinkToolConnectAction = new global::TransactionKernelDSL.Framework.Language.TransactionHandlerMaintenanceLinkToolConnectAction(this);
						this.transactionHandlerMaintenanceLinkToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.transactionHandlerMaintenanceLinkToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TransactionKernelDSL.Framework.Language.TrnxDslToolboxHelper.TransactionSQLServerDataSourceLinkConnectionToolFilterString))
				{
					if (this.transactionSQLServerDataSourceLinkConnectionToolConnectAction == null)
					{
						this.transactionSQLServerDataSourceLinkConnectionToolConnectAction = new global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceLinkConnectionToolConnectAction(this);
						this.transactionSQLServerDataSourceLinkConnectionToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.transactionSQLServerDataSourceLinkConnectionToolConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.outputWebServiceLinkToolConnectAction != null)
					{
						this.outputWebServiceLinkToolConnectAction.Dispose();
						this.outputWebServiceLinkToolConnectAction = null;
					}
					if(this.timeTriggerLinkToolConnectAction != null)
					{
						this.timeTriggerLinkToolConnectAction.Dispose();
						this.timeTriggerLinkToolConnectAction = null;
					}
					if(this.inputLinkToolConnectAction != null)
					{
						this.inputLinkToolConnectAction.Dispose();
						this.inputLinkToolConnectAction = null;
					}
					if(this.outputLinkToolConnectAction != null)
					{
						this.outputLinkToolConnectAction.Dispose();
						this.outputLinkToolConnectAction = null;
					}
					if(this.transactionDataSourceSupportForOutputEngineLinkToolConnectAction != null)
					{
						this.transactionDataSourceSupportForOutputEngineLinkToolConnectAction.Dispose();
						this.transactionDataSourceSupportForOutputEngineLinkToolConnectAction = null;
					}
					if(this.transactionHandlerForwardingLinkToolConnectAction != null)
					{
						this.transactionHandlerForwardingLinkToolConnectAction.Dispose();
						this.transactionHandlerForwardingLinkToolConnectAction = null;
					}
					if(this.transactionHandlerMaintenanceLinkToolConnectAction != null)
					{
						this.transactionHandlerMaintenanceLinkToolConnectAction.Dispose();
						this.transactionHandlerMaintenanceLinkToolConnectAction = null;
					}
					if(this.transactionSQLServerDataSourceLinkConnectionToolConnectAction != null)
					{
						this.transactionSQLServerDataSourceLinkConnectionToolConnectAction.Dispose();
						this.transactionSQLServerDataSourceLinkConnectionToolConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// TrnxDslDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x77f68ba6, 0x65e6, 0x488c, 0xa7, 0xbb, 0x22, 0x8f, 0x13, 0x95, 0x1e, 0xb1);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TrnxDslDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TrnxDslDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace TransactionKernelDSL.Framework.Language
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngine), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionWebService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandler), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionWebService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesTransactionSQLServerDataSources), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesMaintenanceTransactionHandler), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariable), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTimeTriggers), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TimeTrigger), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionLayer), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesForwarderTransactionHandlers), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineReferencesTransactionDataSourceSupport), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.InputTransactionEngine)
				{
					parentElement = GetParentForInputTransactionEngine((global::TransactionKernelDSL.Framework.Language.InputTransactionEngine)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine)
				{
					parentElement = GetParentForOutputTransactionEngine((global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource)
				{
					parentElement = GetParentForTransactionSQLServerDataSource((global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.OutputTransactionWebService)
				{
					parentElement = GetParentForOutputTransactionWebService((global::TransactionKernelDSL.Framework.Language.OutputTransactionWebService)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.TransactionHandler)
				{
					parentElement = GetParentForTransactionHandler((global::TransactionKernelDSL.Framework.Language.TransactionHandler)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer)
				{
					parentElement = GetParentForTransactionEnvironmentLayer((global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariable)
				{
					parentElement = GetParentForTransactionEnvironmentSQLServerVariable((global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariable)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport)
				{
					parentElement = GetParentForTransactionDataSourceSupport((global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.TimeTrigger)
				{
					parentElement = GetParentForTimeTrigger((global::TransactionKernelDSL.Framework.Language.TimeTrigger)childElement);
				} else
				if(childElement is global::TransactionKernelDSL.Framework.Language.TransactionLayer)
				{
					parentElement = GetParentForTransactionLayer((global::TransactionKernelDSL.Framework.Language.TransactionLayer)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionModel GetParentForTransactionHandler( global::TransactionKernelDSL.Framework.Language.TransactionHandler root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionLayer root2 = root.TransactionLayer;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::TransactionKernelDSL.Framework.Language.TransactionModel result = root2.TransactionModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionModel GetParentForTransactionLayer( global::TransactionKernelDSL.Framework.Language.TransactionLayer root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionModel result = root.TransactionModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionModel GetParentForInputTransactionEngine( global::TransactionKernelDSL.Framework.Language.InputTransactionEngine root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionLayer root2 = root.TransactionLayer;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::TransactionKernelDSL.Framework.Language.TransactionModel result = root2.TransactionModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionModel GetParentForOutputTransactionEngine( global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionLayer root2 = root.TransactionLayer;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::TransactionKernelDSL.Framework.Language.TransactionModel result = root2.TransactionModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionLayer GetParentForTransactionSQLServerDataSource( global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionLayer result = root.TransactionLayer;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionLayer GetParentForOutputTransactionWebService( global::TransactionKernelDSL.Framework.Language.OutputTransactionWebService root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionLayer result = root.TransactionLayer;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionLayer GetParentForTimeTrigger( global::TransactionKernelDSL.Framework.Language.TimeTrigger root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionLayer result = root.TransactionLayer;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionModel GetParentForTransactionDataSourceSupport( global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionLayer root2 = root.TransactionLayer;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::TransactionKernelDSL.Framework.Language.TransactionModel result = root2.TransactionModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionModel GetParentForTransactionEnvironmentLayer( global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionModel result = root.TransactionModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TransactionKernelDSL.Framework.Language.TransactionModel GetParentForTransactionEnvironmentSQLServerVariable( global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariable root )
			{
				// Segments 0 and 1
				global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer root2 = root.TransactionEnvironmentLayer;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::TransactionKernelDSL.Framework.Language.TransactionModel result = root2.TransactionModel;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers)
				{
					global::System.Collections.IEnumerable elements = GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers)e.ModelElement);
					UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape), "TransactionHandler", repaintOnly);
				}
				if(e.ModelElement is global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine)
				{
					global::System.Collections.IEnumerable elements = GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine)e.ModelElement);
					UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape), "TransactionHandler", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandlerFromLastLink(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers root)
			{
				// Segment 0
				global::TransactionKernelDSL.Framework.Language.InputTransactionEngine result = root.InputTransactionEngine;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandler(global::TransactionKernelDSL.Framework.Language.TransactionHandler root)
			{
				// Segments 1 and 0
				global::TransactionKernelDSL.Framework.Language.InputTransactionEngine result = root.InputTransactionEngine;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandlerFromLastLink(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine root)
			{
				// Segment 0
				global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine result = root.OutputTransactionEngine;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandler(global::TransactionKernelDSL.Framework.Language.TransactionHandler root)
			{
				// Segments 1 and 0
				global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine result = root.OutputTransactionEngine;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape), "TransactionHandler", repaintOnly);
				}
				if(e.ModelElement is global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape), "TransactionHandler", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandler), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::TransactionKernelDSL.Framework.Language.TransactionHandler && e.DomainProperty.Id == global::TransactionKernelDSL.Framework.Language.TransactionHandler.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandler((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape), "TransactionHandler", repaintOnly);
				}
				if(e.ModelElement is global::TransactionKernelDSL.Framework.Language.TransactionHandler && e.DomainProperty.Id == global::TransactionKernelDSL.Framework.Language.TransactionHandler.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandler((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape), "TransactionHandler", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape compartmentShape = pel as global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape), "TransactionHandler", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandler((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape), "TransactionHandler", repaintOnly);
					}
				}
				if(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape compartmentShape = pel as global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandlerFromLastLink((global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape), "TransactionHandler", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandler((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape), "TransactionHandler", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInputTransactionEngineForInputTransactionEngineShapeTransactionHandler((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineShape), "TransactionHandler", repaintOnly);
					}
				}
				if(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetOutputTransactionEngineForOutputTransactionEngineShapeTransactionHandler((global::TransactionKernelDSL.Framework.Language.TransactionHandler)e.SourceElement);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineShape), "TransactionHandler", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionDataSource), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TimeTrigger), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::TransactionKernelDSL.Framework.Language.TransactionDataSource.NameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::TransactionKernelDSL.Framework.Language.TransactionDataSourceShape.FindTransactionDataSourceShapeDecorator("NameDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::TransactionKernelDSL.Framework.Language.TransactionDataSource.StepOrderDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::TransactionKernelDSL.Framework.Language.TransactionDataSourceShape.FindTransactionDataSourceShapeDecorator("StepOrderDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::TransactionKernelDSL.Framework.Language.TimeTrigger.NameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::TransactionKernelDSL.Framework.Language.TimeTriggerImageShape.FindTimeTriggerImageShapeDecorator("NameDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::TransactionKernelDSL.Framework.Language.TimeTrigger.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport.NameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportShape.FindTransactionDataSourceSupportShapeDecorator("NameDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesForwarderTransactionHandlers), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesMaintenanceTransactionHandler), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionEngine), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTransactionHandlers), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesTransactionSQLServerDataSources), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.TransactionHandlerReferencesOutputTransactionWebService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.InputTransactionEngineReferencesTimeTriggers), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TransactionKernelDSL.Framework.Language.OutputTransactionEngineReferencesTransactionDataSourceSupport), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::TransactionKernelDSL.Framework.Language.TrnxDslDiagram diagram = linkShape.Diagram as global::TransactionKernelDSL.Framework.Language.TrnxDslDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
