//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace TransactionKernelDSL.Framework.Language
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class TrnxDslToolboxHelper : TrnxDslToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new TrnxDslToolboxHelper.
		/// </summary>
		public TrnxDslToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class TrnxDslToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify TrnxDsl toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "TrnxDsl.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify OutputWebServiceLinkTool connector tool.
		/// </summary>
		public const string OutputWebServiceLinkToolFilterString = "OutputWebServiceLinkTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify TimeTriggerLinkTool connector tool.
		/// </summary>
		public const string TimeTriggerLinkToolFilterString = "TimeTriggerLinkTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify InputLinkTool connector tool.
		/// </summary>
		public const string InputLinkToolFilterString = "InputLinkTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify OutputLinkTool connector tool.
		/// </summary>
		public const string OutputLinkToolFilterString = "OutputLinkTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify TransactionDataSourceSupportForOutputEngineLinkTool connector tool.
		/// </summary>
		public const string TransactionDataSourceSupportForOutputEngineLinkToolFilterString = "TransactionDataSourceSupportForOutputEngineLinkTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify TransactionHandlerForwardingLinkTool connector tool.
		/// </summary>
		public const string TransactionHandlerForwardingLinkToolFilterString = "TransactionHandlerForwardingLinkTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify TransactionHandlerMaintenanceLinkTool connector tool.
		/// </summary>
		public const string TransactionHandlerMaintenanceLinkToolFilterString = "TransactionHandlerMaintenanceLinkTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify TransactionSQLServerDataSourceLinkConnectionTool connector tool.
		/// </summary>
		public const string TransactionSQLServerDataSourceLinkConnectionToolFilterString = "TransactionSQLServerDataSourceLinkConnectionTool.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new TrnxDslToolboxHelperBase.
		/// </summary>
		protected TrnxDslToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel.SingletonResourceManager.GetString("Transaction Model ElementsToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 4;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "TransactionKernelDSL.Framework.Language.OutputWebServiceLinkToolToolboxItem":

					// Add OutputWebServiceLinkTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.OutputWebServiceLinkToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OutputWebServiceLinkToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OutputWebServiceLinkToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Transaction Model ElementsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"OutputWebServiceLinkTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OutputWebServiceLinkToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(OutputWebServiceLinkToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.OutputWebServiceToolToolboxItem":
					// Add OutputWebServiceTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.OutputWebServiceToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OutputWebServiceToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OutputWebServiceToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Transaction Model ElementsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"OutputWebServiceTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OutputWebServiceToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.OutputTransactionWebService.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TimeTriggerToolToolboxItem":
					// Add TimeTriggerTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TimeTriggerToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TimeTriggerToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TimeTriggerToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Transaction Model ElementsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TimeTriggerTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TimeTriggerToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.TimeTrigger.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TimeTriggerLinkToolToolboxItem":

					// Add TimeTriggerLinkTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TimeTriggerLinkToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TimeTriggerLinkToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TimeTriggerLinkToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.Transaction Model ElementsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Transaction Model ElementsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TimeTriggerLinkTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TimeTriggerLinkToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(TimeTriggerLinkToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.InputTransactionEngineToolToolboxItem":
					// Add InputTransactionEngineTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.InputTransactionEngineToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InputTransactionEngineToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InputTransactionEngineToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.EnginesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnginesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"InputTransactionEngineTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InputTransactionEngineToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.InputTransactionEngine.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.InputLinkToolToolboxItem":

					// Add InputLinkTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.InputLinkToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InputLinkToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InputLinkToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.EnginesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnginesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"InputLinkTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InputLinkToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(InputLinkToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.OutputTransactionEngineToolToolboxItem":
					// Add OutputTransactionEngineTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.OutputTransactionEngineToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OutputTransactionEngineToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OutputTransactionEngineToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.EnginesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnginesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"OutputTransactionEngineTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OutputTransactionEngineToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.OutputTransactionEngine.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.OutputLinkToolToolboxItem":

					// Add OutputLinkTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.OutputLinkToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OutputLinkToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OutputLinkToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.EnginesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnginesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"OutputLinkTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OutputLinkToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(OutputLinkToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportForOutputEngineLinkToolToolboxItem":

					// Add TransactionDataSourceSupportForOutputEngineLinkTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportForOutputEngineLinkToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionDataSourceSupportForOutputEngineLinkToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionDataSourceSupportForOutputEngineLinkToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.EnginesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnginesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionDataSourceSupportForOutputEngineLinkTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionDataSourceSupportForOutputEngineLinkToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(TransactionDataSourceSupportForOutputEngineLinkToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionHandlerToolToolboxItem":
					// Add TransactionHandlerTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionHandlerToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionHandlerToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionHandlerToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.HandlersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("HandlersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CreateExampleClassF1Keyword", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionHandlerToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.TransactionHandler.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionHandlerForwardingLinkToolToolboxItem":

					// Add TransactionHandlerForwardingLinkTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionHandlerForwardingLinkToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionHandlerForwardingLinkToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionHandlerForwardingLinkToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.HandlersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("HandlersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ConnectExampleRelationF1Keyword", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionHandlerForwardingLinkToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(TransactionHandlerForwardingLinkToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionHandlerMaintenanceLinkToolToolboxItem":

					// Add TransactionHandlerMaintenanceLinkTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionHandlerMaintenanceLinkToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionHandlerMaintenanceLinkToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionHandlerMaintenanceLinkToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.HandlersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("HandlersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionHandlerMaintenanceLinkTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionHandlerMaintenanceLinkToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(TransactionHandlerMaintenanceLinkToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceLinkConnectionToolToolboxItem":

					// Add TransactionSQLServerDataSourceLinkConnectionTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceLinkConnectionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionSQLServerDataSourceLinkConnectionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionSQLServerDataSourceLinkConnectionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"TransactionKernelDSL.Framework.Language.HandlersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("HandlersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionSQLServerDataSourceLinkConnectionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionSQLServerDataSourceLinkConnectionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(TransactionSQLServerDataSourceLinkConnectionToolFilterString)
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionLayerToolToolboxItem":
					// Add TransactionLayerTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionLayerToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionLayerToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionLayerToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionLayerTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionLayerToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.TransactionLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayerToolToolboxItem":
					// Add TransactionEnvironmentLayerTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayerToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionEnvironmentLayerToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionEnvironmentLayerToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionEnvironmentLayerTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionEnvironmentLayerToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceToolToolboxItem":
					// Add TransactionSQLServerDataSourceTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSourceToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionSQLServerDataSourceToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionSQLServerDataSourceToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.Data SourcesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data SourcesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionSQLServerDataSourceTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionSQLServerDataSourceToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.TransactionSQLServerDataSource.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportToolToolboxItem":
					// Add TransactionDataSourceSupportTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionDataSourceSupportToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionDataSourceSupportToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionDataSourceSupportToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.Data SourcesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data SourcesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionDataSourceSupportTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionDataSourceSupportToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.TransactionDataSourceSupport.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariableToolToolboxItem":
					// Add TransactionEnvironmentSQLServerVariableTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariableToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TransactionEnvironmentSQLServerVariableToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TransactionEnvironmentSQLServerVariableToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"TransactionKernelDSL.Framework.Language.EnvironmentToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnvironmentToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TransactionEnvironmentSQLServerVariableTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TransactionEnvironmentSQLServerVariableToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::TransactionKernelDSL.Framework.Language.TransactionEnvironmentSQLServerVariable.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::TransactionKernelDSL.Framework.Language.TrnxDslDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
